### ISSUE TITLE
Disclaimer and License

### ISSUE THREAD

**Issue by Kourtney-Burger** [nmfs-ost/PAM_template_lab_manual#3]
https://github.com/nmfs-ost/PAM_template_lab_manual/blob/5da100fd8d092f8778102307bb291b607efbe9be/README.md?plain=1#L3-L9

I left the readMe disclaimer and license the same as the NMFS OpenSci template. Do we need to tweak it or is it just a general statement?

**Comment by shannonrankin** [comment]
Yes, disclaimer notice is general and it's ok to leave in as is.  Same with License (at this time).
