### ISSUE TITLE
Reporting Page

### ISSUE THREAD

**Issue by Kourtney-Burger** [nmfs-ost/PAM_template_lab_manual#4]
Is this the page for lab publications and presentations? What else should be included here?

**Comment by rebecca-vanhoeck** [comment]
We could include publications and presentations here, but this was more intended for templates for reporting to other agencies/within NOAA. For example, NEFSC has multiple [PAM data reporting templates](https://www.fisheries.noaa.gov/resource/document/passive-acoustic-reporting-system-templates) that are provided to the OSW developers and RWSC - these would likely go on the national page. We also have a standard report format for a few different agencies/species (right whales, Australian Marine Parks.) to include on the NEFSC page.

**Comment by Kourtney-Burger** [comment]
Thanks Becca, that makes more sense! I added an optional page for publications and presentations so I will keep that and add this information to the reporting page
