### ISSUE TITLE
Goals

### ISSUE THREAD

**Issue by Kourtney-Burger** [nmfs-ost/PAM_template_lab_manual#5]
How does this sound for the introduction/goals for this template? Is there anything you want to add here? 

https://github.com/nmfs-ost/PAM_template_lab_manual/blob/8f72c8685597bdd147198b92b4f94c2630e89b7b/index.qmd#L7-L9

**Comment by rebecca-vanhoeck** [comment]
Hi Kourtney - thanks! Here's a suggested edit to the goals section: 

A key priority of the PAM SI is to build an open science culture across the agency by leveraging GitHub as a collaboration, coordination, and project management tool. To achieve this we will develop national and regional lab manuals that follow a parallel structure and link to each other. These manuals will serve as the primary storage location for all lab related information, including methods and data management, and will be a single access resource to support coordination across science center PAM programs.

**Comment by Kourtney-Burger** [comment]
Thanks Becca!
