### ISSUE TITLE
Image not rendering

### ISSUE THREAD

**Issue by Kourtney-Burger** [nmfs-ost/PAM_template_lab_manual#8]
@shannonrankin This image is not rendering for me. Can you see it on your end? 

https://github.com/nmfs-ost/PAM_template_lab_manual/blob/c57b01823ecde5a946f8a1453eb6f79109191258/content/NMFS_OpenSciDirections/add-content.qmd#L35-L37

**Comment by shannonrankin** [comment]
Ok, I think I fixed it!

**Comment by Kourtney-Burger** [comment]
Looks good!
